[WIP] Feat account
penguin-statistics/backend pull request #61
Opened 2020-12-30 15:09 UTC by martinwang2002

Oauth2 account
#11

2020-12-30 15:14 UTC, martinwang2002 commented
- [ ] application.yml contains oauth2 tokens, require CD to fix.

2021-01-06 18:46 UTC, ChoKhoOu requested changes

2021-01-06 18:46 UTC, ChoKhoOu commented on src/main/java/io/penguinstats/controller/v2/api/UserController.java
> +							|| redirectURIHost == "penguin-stats.io") {
还是别用 “==”了吧  (x  ，  最好还是用equal ， 另外就是后面两个Host的对比值都是一样的   [○･｀Д´･ ○]

2021-01-06 18:46 UTC, ChoKhoOu commented on src/main/java/io/penguinstats/util/CookieUtil.java
> +				if (cookie.getName().equals("oauth2State")) {
这里存在NPE的可能 ， 最好的方式是改成 
```java
 if ("oauth2State".equals(cookie.getName()))
```

2021-01-06 18:46 UTC, ChoKhoOu commented on src/main/resources/application.yml
> +    Google:
这里不要commit上来， 不安全。这样的话，随便一个人都直接能用我们企鹅的id跟secret了

2021-01-07 02:31 UTC, martinwang2002 commented on src/main/java/io/penguinstats/util/CookieUtil.java
> +				if (cookie.getName().equals("oauth2State")) {
Also fix for cookie `userID`

2021-01-07 02:33 UTC, martinwang2002 commented on src/main/resources/application.yml
> +    Google:
这不是生产用的token，本意是方便测试，并且只有授权的账号才可登录。现已移除。

2022-03-04 19:30 UTC, closed without merging